CI: add png to generated files list

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -152,7 +152,7 @@ jobs:
           echo "=== END-TO-END TESTS DEBUG ==="
 
           echo "Files in end-to-end/:"
-          find ./end-to-end/ -type f -not -path "*/node_modules/*" -not -path "*/.*"  \( -name "*.json" -o -name "*.html" -o -name "*.mp4 -o -name "*.cy.ts"" \) 2>/dev/null || echo "ERROR: No e2E test directory found"
+          find ./end-to-end/ -type f -not -path "*/node_modules/*" -not -path "*/.*"  \( -name "*.json" -o -name "*.html" -o -name "*.mp4 -o -name "*.cy.ts" -o -name "*.png" \) 2>/dev/null || echo "ERROR: No e2E test directory found"
 
           echo -e "\n######################################\n"
 
@@ -288,7 +288,7 @@ jobs:
           echo "=== END-TO-END NONREG DEBUG ==="
 
           echo "Files in end-to-end/:"
-          find ./end-to-end -type f -not -path "*/node_modules/*" -not -path "*/.*" \( -name "*.json" -o -name "*.html" -o -name "*.mp4" -o -name "*.cy.ts" \) 2>/dev/null || echo "ERROR: No e2E test files found"
+          find ./end-to-end -type f -not -path "*/node_modules/*" -not -path "*/.*" \( -name "*.json" -o -name "*.html" -o -name "*.mp4" -o -name "*.cy.ts" -o -name "*.png" \) 2>/dev/null || echo "ERROR: No e2E test files found"
 
           echo -e "\n######################################\n"
 
